apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: bopgeek/:v1latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
              memory: "500Mi"
              cpu: "500m"
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        #   initialDelaySeconds: 60
        #   periodSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        #   initialDelaySeconds: 60
        #   periodSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   timeoutSeconds: 10
